### ISSUE TITLE
Add Feature to switch games without disconnecting/reconnecting the Virtual Display

### ISSUE THREAD

**Issue by LeGeRyChEeSe** [Cynary/sunshine-virtual-monitor#1]
Thank you so much for this script you made, it’s really helpful.

Now that i'm using it for a while i wanted to request you such a little feature to enhance the user experience and avoid some useless operations.

Can you add the feature of letting the virtual display on when just switching a game ?

That would be amazing.

**Comment by Cynary** [comment]
Hi,

Could you go into more detail on what you're looking for, and what you mean by "just switching a game"?

If you mean switching a game from the client side, then I don't think there's much we can do to detect that right now - that involves moonlight stopping and starting the stream, afaict there isn't a way to distinguish between the stream shutting down long term, and switching a game.

Though, if you can provide more details on what you envision the workflow to be, I could look into it.

**Comment by LeGeRyChEeSe** [comment]
It’s effectively from the Moonlight side that i want to switch games and if there is no way to distinguish both switching and stopping games then i should see with moonlight itself to request this feature.

**Comment by Cynary** [comment]
I'll double to make sure I'm not missing some variable that might signal this, but if not, then yeah there's not much we can do :/
What I typically do is to use launchers (steam big picture and playnite are popular ones) to switch games without leaving the host - if the launcher stays up, the stream doesn't shutdown.

**Comment by Cynary** [comment]
Thank you for your contributions on this - your AIO collection is really neat :)
