### ISSUE TITLE
alt+enter doesn't enter fullscreen.

### ISSUE THREAD

**Issue by squarepizza1** [Cynary/sunshine-virtual-monitor#11]
Pressing alt+enter won't change a window to fullscreen. If I stop streaming to my Steam Deck, the shortcut will start working again.

**Comment by Cynary** [comment]
Hi,
I don't see how virtual displays could cause this - even if it can, there's not much I can do to support it unless you have evidence it's something in the scripts in this repository. Some things you should try:

1. Does alt+enter work if you don't use the virtual display at all, and just stream from your regular display?
2. If you setup a virtual display without using the scripts in this repository, does alt+enter work?

If either of those has the answer "No", then the issue isn't with these scripts - you would need to get help with either (1) sunshine/moonlight, or (2) virtual display driver.

**Comment by squarepizza1** [comment]
alt+enter works if I don't use cmd /C powershell.exe -executionpolicy bypass -windowstyle hidden -file "%PATH_TO_THIS_REPOSITORY%\setup_sunvdm.ps1" %SUNSHINE_CLIENT_WIDTH% %SUNSHINE_CLIENT_HEIGHT% %SUNSHINE_CLIENT_FPS% %SUNSHINE_CLIENT_HDR% > "%PATH_TO_THIS_REPOSITORY%\sunvdm.log" 2>&1
and cmd /C powershell.exe -executionpolicy bypass -windowstyle hidden -file "%PATH_TO_THIS_REPOSITORY%\teardown_sunvdm.ps1" >> "%PATH_TO_THIS_REPOSITORY%\sunvdm.log" 2>&1

**Comment by Cynary** [comment]
Hi,

So, if you remove the commands, alt+enter works - do you use alt+enter to fullscreen some specific application?

But with the commands in place, it doesn't work.

Have you tried removing the commands, but setting up a virtual display, and while streaming removing all other display so that the virtual display is your primary display (also, make sure to undo that before finishing the stream, otherwise your host's display won't show anything)? Does alt+enter work then?

**Comment by squarepizza1** [comment]
If I try to use a virtual display, it loads for a long time, then gives me error 0.

**Comment by Cynary** [comment]
So, without using the scripts in this repository, if you setup a virtual display and use it, alt+enter doesn't work?

Unfortunately, there's not much we can do about that :/ the code here is only for automation to manage the virtual display, not for the virtual display driver itself, which sounds like it's the source of the issue - it might be better to ask in the https://github.com/itsmikethetech/Virtual-Display-Driver project, they might have some better idea of what to do.

I'll close in a couple of days if there's no extra questions - let me know if my understanding is correct that it doesn't work even when these scripts aren't involved.

**Comment by squarepizza1** [comment]
I'll open an issue there.
