### ISSUE TITLE
Windows 11 24H2 error: This command is not supported on this OS product. 

### ISSUE THREAD

**Issue by GiovanyUK** [Cynary/sunshine-virtual-monitor#5]
basically the title. this is what the log says: 

```
Setting up a moonlight monitor with 1280x800@90 with hdr on
Enabling the virtual display.
Microsoft PnP Utility

Failed to enable device:  ROOT\DISPLAY\0001
Device is already enabled.

This command is not supported on this OS product.
Setting up the virtual display and disabling other displays.
Disabling all other displays.
True
```

I mention that I updated windows from 22H2 to 24H2,  before it used to work but I didn't have HDR available so I updated, the CMD prompt usually appears and then disapears without anything happening (only the main screen's cursor starts to glich out every couple of seconds) 

Also I mention that I've played a lot with the registry and stuff and so it might be a really big "me problem" but maybe someone more tech savy can find out exactly what I might have did wrong. But again, before updating it worked, after updating it didnt work anymore so I tried doing all steps again but it didnt help

**Comment by sysmoon14** [comment]
I'm just trying this script for the first time and I'm seeing issues disabling my non virtual monitors.

Also on 24H2, could be MultiMonitorTool not compatible?

**Comment by Cynary** [comment]
I wonder if this could be related to #6 - maybe it's a new failure type on 24H2, and you hit it as part of rebooting after the update.
You can try my workaround there to see if it matches - basically, since the vdd didn't get enabled, windows won't let you disable your non-virtual displays; the underlying issue, though, is the failure to enable the VDD.

**Comment by Cynary** [comment]
@sysmoon14 @GiovanyUK when you have a chance, please check if the new changes fix this issue.

**Comment by Cynary** [comment]
Closing, assuming the recent changes fix the issue - feel free to open a new issue if not.
