### ISSUE TITLE
Script Doesn't Work After Reboot

### ISSUE THREAD

**Issue by sysmoon14** [Cynary/sunshine-virtual-monitor#6]
When I first boot (or restart) windows, the script doesn't work. I need to manually enable the virtual display adapter in device management, then disable it again. After I've done that all works smoothly.

If I try to stream before performing the above manual steps I get an error in the log telling me that it failed to enable the device because the device is not connected.

```
Failed to enable device:  ROOT\DISPLAY\0000
The device is not connected.
```

**Comment by MarcioFCMartins** [comment]
I have exactly the same issue, running win 11 with two physical displays. Unfortunately I don't know enough to figure out where to even begin looking for the source of the issue, but if anyone does, let me know and I'll send any info required.

**Comment by Cynary** [comment]
We have a fix incoming for this, but in the meantime you can manually fix it by going into control panel, and manually enabling the virtual display device, and then you can disable it. 
It's possible when you manually enable it, that your screens will be disconnected - you can undo that with windows+P, or connect via sunshine, and on disconnect the script should disable the vdd device.
